export const masConocimientos = [
    {nombre: 'Algebra lineal', categoria: 'Matematicas'},
    {nombre: 'Calculo', categoria: 'Matematicas'},
    {nombre: 'Campo electrico, campo magnetico y ondas (electromagnetismo)', categoria: 'Matematicas'},
    {nombre: 'Principios físicos de los semiconductores y dispositivos fontónicos', categoria: 'Matematicas'},
    {nombre: 'Circuitos eléctricos', categoria: 'Matematicas'},
    {nombre: 'Grafos y algoritmos de arboles', categoria: 'Matematicas'},
    {nombre: 'Estadistica', categoria: 'Matematicas'},

    {nombre: 'Logica computacional', categoria: 'Logica'},
    {nombre: 'Operaciones con codigo binario', categoria: 'Logica'},
    {nombre: 'Electronica digital', categoria: 'Logica'},
    {nombre: 'Circuitos electronicos digitales', categoria: 'Logica'},
    {nombre: 'Funcionamiento de las diferentes unidades funcionales del computador', categoria: 'Logica'},
    {nombre: 'Sistemas operativos', categoria: 'Logica'},
    {nombre: 'Redes de computadores', categoria: 'Logica'},
    {nombre: 'Analisis de rendimiento', categoria: 'Logica'},
    {nombre: 'Computacion paralela', categoria: 'Logica'},

    {nombre: 'Git', categoria: 'Programacion'},
    {nombre: 'Github', categoria: 'Programacion'},
    {nombre: 'Diseño de bases de datos', categoria: 'Programacion'},
    {nombre: 'Desarrollo y mantenimiento de bases de datos relacionales', categoria: 'Programacion'},
    {nombre: 'Estructuras de datos', categoria: 'Programacion'},
    {nombre: 'Paradigma programacion funcional', categoria: 'Programacion'},
    {nombre: 'Paradigma programacion orientada a objetos', categoria: 'Programacion'},
    {nombre: 'Paradigma imperativo de programacion', categoria: 'Programacion'},
    {nombre: 'Técnicas de diseño de algoritmos', categoria: 'Programacion'},
    {nombre: 'Eficiencia de algoritmos', categoria: 'Programacion'},
    {nombre: 'Diseño de arquitecturas en sistemas distribuidos', categoria: 'Programacion'},
    {nombre: 'Implementacion aplicaciones distribuidas', categoria: 'Programacion'},
    {nombre: 'Sockets, protocolos de comunicación, kafka, seguridad, servicios web', categoria: 'Programacion'},
    {nombre: 'Utilizacion servicios de terceros (consumo de API REST de terceros)', categoria: 'Programacion'},
    {nombre: 'Implementacion de servicios propios (implementacion de API REST)', categoria: 'Programacion'},

    {nombre: 'Sistemas de información y tecnologías de la información', categoria: 'Otros'},
    {nombre: 'Manejo de VirtualBox', categoria: 'Otros'},
    {nombre: 'Instalacion de sistemas operativos en maquinas virtuales', categoria: 'Otros'},
    {nombre: 'Diagramas UML y subtipos', categoria: 'Otros'},
    {nombre: 'Inteligencia artificial y vision inteligente', categoria: 'Otros'},
    {nombre: 'Redes neuronales', categoria: 'Otros'},
    {nombre: 'Paradigmas de desarrollo software', categoria: 'Otros'},
    {nombre: 'Testing de sistemas software', categoria: 'Otros'},
    {nombre: 'Gestion de proyectos software', categoria: 'Otros'},
];